services:
  api-todo-pg:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRESQL_USERNAME=todo-list
      - POSTGRESQL_PASSWORD=password
      - POSTGRESQL_DATABASE=node-todo-project
    volumes:
      - ../database:/var/lib/mysql
    networks:
      api-db-network:
        ipv4_address: 172.28.0.3
  api:
    image: "node:18.15-buster"
    build: .
    container_name: "node-todo-project"
    command: sh -c "npm install && npx prisma migrate dev && npm run dev"
    ports:
      - "3333:3333"
      - "5555:5555"
    volumes:
      - ../:/api
    working_dir: /api/
    tty: true
    stdin_open: true
    networks:
      api-db-network:
        ipv4_address: 172.28.0.2
    depends_on:
      - api-todo-pg

    
  
networks:
  api-db-network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.28.0.0/16"
          gateway: "172.28.5.254"